// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzZm1MPWltZPITBbAUa6s0cBnOee2mBtU',
    appId: '1:879935450731:web:41785d7f92867cab99cb2e',
    messagingSenderId: '879935450731',
    projectId: 'chatappproject-d4b35',
    authDomain: 'chatappproject-d4b35.firebaseapp.com',
    storageBucket: 'chatappproject-d4b35.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkX_9i6zYxCcufv8fsAck-HDZTdRxFK-Q',
    appId: '1:879935450731:android:b5906fbb3d9c938799cb2e',
    messagingSenderId: '879935450731',
    projectId: 'chatappproject-d4b35',
    storageBucket: 'chatappproject-d4b35.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwmH9y00YcqzQlO23T9roesDkXdVfvyCY',
    appId: '1:879935450731:ios:6cd9e5e58798fada99cb2e',
    messagingSenderId: '879935450731',
    projectId: 'chatappproject-d4b35',
    storageBucket: 'chatappproject-d4b35.firebasestorage.app',
    iosBundleId: 'com.example.fChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwmH9y00YcqzQlO23T9roesDkXdVfvyCY',
    appId: '1:879935450731:ios:6cd9e5e58798fada99cb2e',
    messagingSenderId: '879935450731',
    projectId: 'chatappproject-d4b35',
    storageBucket: 'chatappproject-d4b35.firebasestorage.app',
    iosBundleId: 'com.example.fChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzZm1MPWltZPITBbAUa6s0cBnOee2mBtU',
    appId: '1:879935450731:web:119988a57b2d264a99cb2e',
    messagingSenderId: '879935450731',
    projectId: 'chatappproject-d4b35',
    authDomain: 'chatappproject-d4b35.firebaseapp.com',
    storageBucket: 'chatappproject-d4b35.firebasestorage.app',
  );
}
